force-app/main/default/objects/Product2/fields/External_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Product_Id__c</fullName>
    <label>External Product Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Sync_Queue__c/Product_Sync_Queue__c.object-meta.xml
<CustomObject>
    <label>Product Sync Queue</label>
    <nameField>
        <label>Product Sync Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sync Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteOperationHandler.cls
public class DeleteOperationHandler implements SyncOperationHandler {
    public HttpRequest createRequest(Product_Sync_Queue__c item, Product2 product) {
        HttpRequest req = new HttpRequest();
        String extId = String.isNotBlank(product.External_Product_Id__c) ? product.External_Product_Id__c : product.Id;
        
        req.setEndpoint(Util.PRODUCT_SYNC_QUEUE.ENDPOINT_URL + extId);
        req.setMethod('DELETE');
        return req;
    }
}