force-app/main/default/objects/Discount__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Fixed Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BaseDiscountEvaluator.cls
public abstract class BaseDiscountEvaluator implements DiscountEvaluator {
    public abstract Boolean isApplicable(Discount__c d, OrderContext context);
    
    public virtual Decimal calculateDiscountValue(Discount__c d, List<DiscountService.CartItem> eligibleItems, Decimal eligibleSubtotal) {
        return d.Discount_Type__c == Util.Discount.TYPE_PERCENT 
            ? eligibleSubtotal * (d.Value__c / 100) 
            : d.Value__c;
    }
}